services:
  postgres:
    image: postgres:15
    container_name: ucn_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ucn_database
    ports:
      - "5434:5432"   # ðŸ‘ˆ Cambiado para evitar conflicto con otros Postgres
    volumes:
      - postgres_ucn_data:/var/lib/postgresql/data
    networks:
      - ucn_net

volumes:
  postgres_ucn_data:

networks:
  ucn_net:
